=== discospiff/Website17-7024/WebService/WebService/XML/plants.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="plant">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="genus">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:maxLength value="70"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="species" minOccurs="0" default="spp.">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:maxLength value="60"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="cultivar" minOccurs="0">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:maxLength value="60"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="common_name" minOccurs="0">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:maxLength value="100"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="height" minOccurs="0" default="0">
          <xs:simpleType>
            <xs:restriction base="xs:integer">
              <xs:maxInclusive value="100"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="begin_bloom_date" type="xs:date" minOccurs="0"/>
        <xs:element name="end_bloom_date" type="xs:date" minOccurs="0"/>
        <xs:element name="edible" type="xs:boolean" minOccurs="0"/>
        <xs:element name="sun_tolerance" minOccurs="0">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:enumeration value="full_sun"/>
              <xs:enumeration value="part_sun"/>
              <xs:enumeration value="part_shade"/>
              <xs:enumeration value="full_shade"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="bloom_color" minOccurs="0">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:enumeration value="red"/>
              <xs:enumeration value="orange"/>
              <xs:enumeration value="yellow"/>
              <xs:enumeration value="blue"/>
              <xs:enumeration value="violet"/>
              <xs:enumeration value="white"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="specimens" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="specimen" type="specimenType"   minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>


  <xs:complexType name="specimenType">
    <xs:sequence>
      <xs:element name="latitude" type="xs:decimal"  minOccurs="0"/>
      <xs:element name="longitude" type="xs:decimal"  minOccurs="0"/>
      <xs:element name="planted_by"  minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="255"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="comments" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string" >
            <xs:maxLength value="1024"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== discospiff/Website17-7024/WebService/WebService/XML/plants.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="plants.xsl"?>
<plant xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="plants.xsd">
	<!-- All payload data belongs here -->
	<foo>bar</foo>
	<genus>Cercis</genus> 
	<species>canadensis</species>
	<common_name>Eastern Redbud</common_name>
	<height>25</height>
	<begin_bloom_date>2017-03-15</begin_bloom_date>
	<end_bloom_date>2017-03-30</end_bloom_date>
	<edible>true</edible>
	<sun_tolerance>full_sun</sun_tolerance>
	<bloom_color>violet</bloom_color>
	<specimens>		
		<specimen>
			<latitude>39.47</latitude>
			<longitude>-84.51</longitude>
			<planted_by>Brandan Jones</planted_by>
			<comments>Beautiful tree!</comments>
		</specimen>
		<specimen>
			<latitude>52.40</latitude>
			<longitude>1.00</longitude>
			<planted_by>Joe Bloggs</planted_by>
			<comments>RBG Kew</comments>
		</specimen>		
		<specimen>
			<latitude>-22.50</latitude>
			<longitude>-68.25</longitude>
			<planted_by>Guillermo Sanchez</planted_by>
			<comments>Lovely Specimen!</comments>
		</specimen>		
		<specimen>
			<latitude>-25.50</latitude>
			<longitude>38.25</longitude>
			<planted_by>Dave Jones</planted_by>
			<comments>wonderful Specimen!</comments>
		</specimen>	
	</specimens>
</plant>
